apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-hello-world
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: hello-world
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
