apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
  labels:
    environment: dev
    type: business-applications
spec:
  description: Development environment for business applications
  
  # Source repositories
  sourceRepos:
  - 'http://s3.devkuban.com/helm-charts'  # MinIO Helm repository
  - 'git@github.com:Bakmurat/Applications.git'  # This repo for app definitions
  - 'https://github.com/Bakmurat/Applications.git'  # HTTPS access for ArgoCD
  
  # Destination clusters and namespaces
  destinations:
  - namespace: 'business-apps-dev'
    server: '*'  # Allow deployment to any cluster
  - namespace: 'argocd'
    server: '*'  # For app-of-apps pattern
    
  # Allow all cluster-level resources
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
    
  # Allow all namespace-level resources
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
    
  # RBAC roles for development environment
  roles:
  - name: dev-admin
    description: Development environment administrators
    policies:
    - p, proj:dev-project:dev-admin, applications, *, dev-project/*, allow
    - p, proj:dev-project:dev-admin, repositories, *, *, allow
    groups:
    - dev-team
    - platform-team
    
  - name: dev-developer
    description: Developers with limited access
    policies:
    - p, proj:dev-project:dev-developer, applications, get, dev-project/*, allow
    - p, proj:dev-project:dev-developer, applications, sync, dev-project/*, allow
    - p, proj:dev-project:dev-developer, applications, action/*, dev-project/*, allow
    groups:
    - developers
    - qa-team
    
  - name: dev-readonly
    description: Read-only access to development
    policies:
    - p, proj:dev-project:dev-readonly, applications, get, dev-project/*, allow
    groups:
    - business-team
    - managers
