apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-project
  namespace: argocd
  labels:
    environment: prod
    type: business-applications
spec:
  description: Production environment for business applications
  
  # Source repositories
  sourceRepos:
  - 'http://s3.devkuban.com/helm-charts'  # MinIO Helm repository
  - 'git@github.com:Bakmurat/Applications.git'  # This repo for app definitions
  - 'https://github.com/Bakmurat/Applications.git'  # HTTPS access for ArgoCD
  
  # Destination clusters and namespaces
  destinations:
  - namespace: 'business-apps-prod'
    server: '*'  # Allow deployment to any cluster
  - namespace: 'argocd'
    server: '*'  # For app-of-apps pattern
    
  # Allow all cluster-level resources
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
    
  # Allow all namespace-level resources
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
    
  # RBAC roles for production environment (strict access)
  roles:
  - name: prod-admin
    description: Production environment administrators
    policies:
    - p, proj:prod-project:prod-admin, applications, *, prod-project/*, allow
    - p, proj:prod-project:prod-admin, repositories, *, *, allow
    groups:
    - sre-team
    - platform-team
    
  - name: prod-operator
    description: Production operators with limited sync access
    policies:
    - p, proj:prod-project:prod-operator, applications, get, prod-project/*, allow
    - p, proj:prod-project:prod-operator, applications, sync, prod-project/*, allow
    - p, proj:prod-project:prod-operator, applications, action/restart, prod-project/*, allow
    groups:
    - prod-operators
    - sre-team
    
  - name: prod-readonly
    description: Read-only access to production
    policies:
    - p, proj:prod-project:prod-readonly, applications, get, prod-project/*, allow
    groups:
    - dev-team
    - qa-team
    - business-team
    - managers
