apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-project
  namespace: argocd
  labels:
    environment: prod
    type: business-applications
spec:
  description: Production environment for business applications
  
  # Source repositories
  sourceRepos:
  - 'http://s3.devkuban.com/helm-charts'  # MinIO Helm repository
  - 'git@github.com:Bakmurat/Applications.git'  # This repo for app definitions
  
  # Destination clusters and namespaces
  destinations:
  - namespace: 'business-apps-prod'
    server: '*'  # Allow deployment to any cluster
  - namespace: 'argocd'
    server: '*'  # For app-of-apps pattern
    
  # Cluster-level resources (minimal for business apps)
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
    
  # Namespace-level resources (business application resources)
  namespaceResourceWhitelist:
  - group: ''
    kind: Service
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: PersistentVolumeClaim
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: ReplicaSet
  - group: ''
    kind: Pod
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  - group: 'autoscaling'
    kind: HorizontalPodAutoscaler
  - group: 'policy'
    kind: PodDisruptionBudget
  - group: 'monitoring.coreos.com'
    kind: ServiceMonitor
  - group: 'external-secrets.io'
    kind: ExternalSecret
  - group: 'external-secrets.io'
    kind: SecretStore
    
  # RBAC roles for production environment (strict access)
  roles:
  - name: prod-admin
    description: Production environment administrators
    policies:
    - p, proj:prod-project:prod-admin, applications, *, prod-project/*, allow
    - p, proj:prod-project:prod-admin, repositories, *, *, allow
    groups:
    - sre-team
    - platform-team
    
  - name: prod-operator
    description: Production operators with limited sync access
    policies:
    - p, proj:prod-project:prod-operator, applications, get, prod-project/*, allow
    - p, proj:prod-project:prod-operator, applications, sync, prod-project/*, allow
    - p, proj:prod-project:prod-operator, applications, action/restart, prod-project/*, allow
    groups:
    - prod-operators
    - sre-team
    
  - name: prod-readonly
    description: Read-only access to production
    policies:
    - p, proj:prod-project:prod-readonly, applications, get, prod-project/*, allow
    groups:
    - dev-team
    - qa-team
    - business-team
    - managers
