apiVersion: v1
kind: Service
metadata:
  name: sample-nginx
  labels:
    app: sample-nginx
spec:
  selector:
    app: sample-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
