# Production Environment Values for simple-redis
replicaCount: 2  # High availability

image:
  repository: redis
  tag: "7.0-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# High availability configuration
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - simple-redis
        topologyKey: kubernetes.io/hostname

podLabels:
  environment: prod
  tier: production

persistence:
  enabled: true
  size: 8Gi
  storageClass: harvester  # Use your available storage class
