apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-prod
  namespace: argocd
  labels:
    environment: prod
spec:
  project: default
  source:
    repoURL: git@github.com:Bakmurat/Applications.git
    targetRevision: HEAD
    path: applications/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
