# Production Cluster Bootstrap for simple-redis
# Deploy this only in the PROD cluster ArgoCD

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-redis-prod
  namespace: argocd
  labels:
    app: simple-redis
    environment: prod
    cluster: prod
    team: business
spec:
  project: prod-project
  source:
    repoURL: http://s3.devkuban.com/helm-charts
    chart: simple-redis
    targetRevision: 1.0.0
    helm:
      values: |
        # Production Environment Values for simple-redis
        replicaCount: 2

        image:
          repository: redis
          tag: "7.0-alpine"
          pullPolicy: IfNotPresent

        service:
          type: ClusterIP
          port: 6379

        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi

        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - simple-redis
                topologyKey: kubernetes.io/hostname

        podLabels:
          environment: prod
          tier: production

  destination:
    server: https://kubernetes.default.svc  # Local cluster (prod)
    namespace: business-apps-prod
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
