apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-hello-world
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: hello-world
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
