apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-redis-prod
  namespace: argocd
  labels:
    app: simple-redis
    environment: prod
    team: business
spec:
  project: prod-project
  source:
    repoURL: http://s3.devkuban.com/helm-charts
    chart: simple-redis
    targetRevision: 1.0.0
    helm:
      values: |
        # Production Environment Values for simple-redis
        # Optimized for production workloads with high availability

        replicaCount: 2  # High availability with multiple replicas

        image:
          repository: redis
          tag: "7.0-alpine"
          pullPolicy: IfNotPresent

        service:
          type: ClusterIP
          port: 6379

        # Production resource limits
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi

        # Production-specific configuration
        nodeSelector: {}
        tolerations: []

        # Pod anti-affinity for high availability
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - simple-redis
                topologyKey: kubernetes.io/hostname

        # Labels for production
        podLabels:
          environment: prod
          tier: production
  destination:
    server: https://kubernetes.default.svc
    namespace: business-apps-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: "Service"
      jsonPointers:
        - /spec/clusterIP
