# UAT Environment Values for simple-redis
replicaCount: 1

image:
  repository: redis
  tag: "7.0-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

podLabels:
  environment: uat
  tier: testing

persistence:
  enabled: false  # Temporary data for testing
