# UAT Environment Values for simple-nginx
replicaCount: 2

image:
  repository: nginx
  tag: "1.21-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

podLabels:
  environment: uat
  tier: testing

env:
  - name: ENVIRONMENT
    value: "uat"
