# UAT Environment Values for simple-redis
# Configuration for user acceptance testing

replicaCount: 1

image:
  repository: redis
  tag: "7.0-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

# UAT resource limits (moderate)
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Labels for UAT
podLabels:
  environment: uat
  tier: testing

# UAT-specific configuration
persistence:
  enabled: false  # Temporary data for testing
