# UAT Environment Values for simple-nginx
# Production-like environment for testing

replicaCount: 2

image:
  repository: nginx
  tag: "1.21-alpine"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

# UAT resource limits - moderate
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# UAT-specific configuration
nodeSelector: {}
tolerations: []
affinity: {}

# Labels for UAT
podLabels:
  environment: uat
  tier: testing

# Environment variable
env:
  - name: ENVIRONMENT
    value: "uat"
