# UAT environment values for webapp
# Stored in this Git repo and referenced by ApplicationSet

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Ingress configuration with SSL
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  tls:
    - secretName: webapp-uat-tls
      hosts:
        - webapp-uat.devkuban.com

# Resource limits for UAT
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Health checks
livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

# UAT-specific settings
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80

networkPolicy:
  enabled: false  # Can be enabled later

persistence:
  enabled: false

# Service account
serviceAccount:
  create: true

# Security context (moderate for UAT)
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1
