apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-hello-world
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: hello-world
        resources:
          requests:
            cpu: 75m
            memory: 96Mi
          limits:
            cpu: 150m
            memory: 192Mi
