# UAT Cluster Bootstrap
# Deploy this only in the UAT cluster ArgoCD

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-uat
  namespace: argocd
  labels:
    app: webapp
    environment: uat
    cluster: uat
    team: business
spec:
  project: uat-project
  source:
    repoURL: http://s3.devkuban.com/helm-charts
    chart: webapp
    targetRevision: 1.0.9
    helm:
      valueFiles:
      - $values/environments/uat/webapp-values.yaml
      values: |
        global:
          environment: uat
          cluster: uat-cluster
        
        replicaCount: 3
        
        image:
          repository: nginx
          pullPolicy: IfNotPresent
          tag: "1.21-alpine"
        
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hosts:
            - host: webapp-uat.devkuban.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: webapp-uat-tls
              hosts:
                - webapp-uat.devkuban.com

  destination:
    server: https://kubernetes.default.svc  # Local cluster (uat)
    namespace: business-apps-uat
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  ignoreDifferences:
    - group: ""
      kind: "Service"
      jsonPointers:
        - /spec/clusterIP
    - group: "apps"
      kind: "Deployment"
      jsonPointers:
        - /spec/replicas
