# Development Environment Values for simple-nginx
replicaCount: 1

image:
  repository: nginx
  tag: "1.21-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

podLabels:
  environment: dev
  tier: development

env:
  - name: ENVIRONMENT
    value: "development"
