# Development Environment Values for simple-redis
replicaCount: 1

image:
  repository: redis
  tag: "7.0-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

podLabels:
  environment: dev
  tier: development

persistence:
  enabled: false  # No persistence needed in dev
