apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-hello-world-dev
  namespace: argocd
  labels:
    app: sample-hello-world
    environment: dev
spec:
  project: default
  source:
    repoURL: git@github.com:Bakmurat/Applications.git
    targetRevision: HEAD
    path: manifests/sample-hello-world/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-apps-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: "Service"
      jsonPointers:
        - /spec/clusterIP
