apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-uat
  namespace: argocd
  labels:
    app: webapp
    environment: uat
    team: business
spec:
  project: uat-project
  source:
    repoURL: http://s3.devkuban.com/helm-charts
    chart: webapp
    targetRevision: 1.0.9
    helm:
      values: |
        # UAT environment configuration
        global:
          environment: uat
          cluster: uat-cluster
        
        # Basic deployment settings
        replicaCount: 3
        
        # Image configuration
        image:
          repository: nginx
          pullPolicy: IfNotPresent
          tag: "1.21-alpine"
        
        # Service configuration
        service:
          type: ClusterIP
          port: 80
          targetPort: 80
        
        # Ingress for UAT with SSL
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hosts:
            - host: webapp-uat.devkuban.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: webapp-uat-tls
              hosts:
                - webapp-uat.devkuban.com
        
        # Resource limits for UAT
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        
        # Health checks
        livenessProbe:
          enabled: true
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        
        readinessProbe:
          enabled: true
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        
        # UAT-specific settings
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 8
          targetCPUUtilizationPercentage: 80
        
        networkPolicy:
          enabled: false  # Can be enabled later
        
        persistence:
          enabled: false
        
        # Service account
        serviceAccount:
          create: true
        
        # Pod disruption budget
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        
        # Security context (moderate for UAT)
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1001
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001

  destination:
    server: https://kubernetes.default.svc
    namespace: business-apps-uat
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  ignoreDifferences:
    - group: ""
      kind: "Service"
      jsonPointers:
        - /spec/clusterIP
    - group: "apps"
      kind: "Deployment"
      jsonPointers:
        - /spec/replicas
