apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-hello-world
  labels:
    app: sample-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-hello-world
  template:
    metadata:
      labels:
        app: sample-hello-world
    spec:
      containers:
      - name: hello-world
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
