apiVersion: v1
kind: Service
metadata:
  name: sample-hello-world
  labels:
    app: sample-hello-world
spec:
  selector:
    app: sample-hello-world
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
